spring.application.name = TripHive_Backend

#DB Connection
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#server.servlet.context-path=/api/v1
#debug=true

#Security
jwt.secret-key=${JWT_SECRET_KEY}

frontend.url=http://localhost:8080
stripe.secret-key=${STRIPE_API_KEY}
stripe.webhook-secret=${STRIPE_WEBHOOK_SECRET}

server.port=${PORT:8080}

server.forward-headers-strategy=framework